Start Solr iff -solr. Added -extsolr.

diff --git a/runcluster/doall b/runcluster/doall
--- a/runcluster/doall
+++ b/runcluster/doall
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 usage() {
-  echo "Usage: $0 (start | stop) [ svc_name ... ] [-options]"
+  echo "Usage: $0 (start | stop) [-options] [ svc_name ... ]"
   echo "  Starts or stops a set of LOCKSS services, either those named on the"
   echo "  command line or the entire set defined in config/services.xxx"
   echo
@@ -19,8 +19,9 @@ usage() {
   echo "  -derby       Use embedded Derby database (default)"
   echo "  -volatile    Use use a volatile artifact index"
   echo "  -dispatching Use use a dispatching artifact index"
-  echo "  -solr <url>  Use external Solr running at the provided base URL"
-  echo "  -solrCollection <name>  Solr collection name to use (default lockss)"
+  echo "  -solr <url>  Use Solr, start and stop with other services"
+  echo "  -extsolr <url>  Use external Solr already listening at <url>"
+  echo "  -solrCollection <name>  Solr collection name to use (default lockss-repo)"
   echo "  -id <file>   Load identity config from <file>"
   echo "               (default config/identity-standalone.xml)"
   echo "  -p lockss:<name>  Load PLN config from"
@@ -83,7 +84,8 @@ max_warc_size=100000000
 volatile_index=
 dispatching_index=
 solr_baseurl=
-solr_collection="lockss"
+start_solr=
+solr_collection="lockss-repo"
 
 declare -A svc_map		# maps svc_name -> jar or artifact
 svc_list=()			# ordered array of svc_name
@@ -148,6 +150,15 @@ run_mvn() {
   mvn $@
 }
 
+# return true iff we should start solr
+is_start_solr() {
+  if [[ -n "${start_solr}" && -n "${svc_map[solr]}" ]]; then
+    return 0;
+  else
+    return 1;
+  fi
+}
+
 # Write service uber jar to temp dir, return (echo) jar name in temp dir
 # copy_jar svc_name jar-file   or
 # copy_jar svc_name mvn:groupid:artifactid:version
@@ -158,16 +169,18 @@ copy_jar() {
       return
       ;;
     solr:* )
-     local version=${2#solr:}
-     local output="${libdir}/solr-${version}.tar.gz"
-     if [ ! -f "${output}" ]; then
-       curl -s https://archive.apache.org/dist/lucene/solr/${version}/solr-${version}.tgz -o "${output}"
-       if [ $? -ne 0 ]; then
-         echo "Couldn't download Solr" >&2
-         return
-       fi
-     fi
+      if is_start_solr; then
+        local version=${2#solr:}
+        local output="${libdir}/solr-${version}.tar.gz"
+        if [ ! -f "${output}" ]; then
+          curl -s https://archive.apache.org/dist/lucene/solr/${version}/solr-${version}.tgz -o "${output}"
+          if [ $? -ne 0 ]; then
+            echo "Couldn't download Solr" >&2
+            return
+          fi
+        fi
      echo "${output}"
+     fi
      ;;
     mvn:* )
       # mvn:artifact - strip "mvn:"
@@ -308,24 +321,25 @@ start_service() {
       extra_args="--spring.config.location=file:${repo_config}"
       ;;
     solr )
-      echo "Starting ${svc_name}"
-      local solr_dir="./solr"
-      local solr_home="${solr_dir}/server/solr"
+      if is_start_solr; then
+        echo "Starting ${svc_name}"
+        local solr_dir="./solr"
+        local solr_home="${solr_dir}/server/solr"
 
-      if [ ! -d "${solr_dir}" ]; then
-        tar xzf "${tmp_jar}" --one-top-level=solr --strip-components=1
-        rm -rf "${solr_home}"
+        if [ ! -d "${solr_dir}" ]; then
+          tar xzf "${tmp_jar}" --one-top-level=solr --strip-components=1
+          rm -rf "${solr_home}"
+        fi
+
+        # Create new Solr home if it doesn't exist
+        if [ ! -d "${solr_home}" ]; then
+          ( cd "${solr_dir}/server"; tar xzf ../../config/solr-home.tar.gz; rm solr/security.json )
+        fi
+
+        # Start Solr service
+        ${solr_dir}/bin/solr start
+        touch ${pid_file}
       fi
-
-      # Create new Solr home if it doesn't exist
-      if [ ! -d "${solr_home}" ]; then
-        ( cd "${solr_dir}/server"; tar xzf ../../config/solr-home.tar.gz; rm solr/security.json )
-      fi
-
-      # Start Solr service
-      ${solr_dir}/bin/solr start
-      touch ${pid_file}
-
       return
       ;;
     * )
@@ -395,17 +409,7 @@ cleanup() {
 
 ### Main ###
 
-# process service name args, if any
-svc_names=
-while [ -n "$1" ]; do
-  case "$1" in
-    -* ) break ;;
-    * ) svc_names="${svc_names} $1"
-	shift; continue ;;
-  esac
-done
-
-while [ -n "$1" ]; do
+while true ; do
   case "$1" in
     "-svcs" )
       svcs_file="$2"
@@ -435,6 +439,10 @@ while [ -n "$1" ]; do
       dispatching_index=1
       shift; continue ;;
     -solr )
+      solr_baseurl="$2"
+      start_solr=1
+      shift; shift; continue ;;
+    -extsolr )
       solr_baseurl="$2"
       shift; shift; continue ;;
     -solrCollection )
@@ -492,11 +500,21 @@ while [ -n "$1" ]; do
     -* )
       other_args="$other_args $1"
       shift; continue ;;
-    * )
-      echo "Unknown option: $1"
-      exit 1 ;;
   esac
   break;
+done
+
+# process service name args, if any
+svc_names=
+while [ -n "$1" ]; do
+  case "$1" in
+    -* )
+      echo "Error: options must be specified before service names"
+      exit 1 ;;
+    * )
+      svc_names="${svc_names} $1"
+      shift; continue ;;
+  esac
 done
 
 case "$verb" in
@@ -549,6 +567,17 @@ else
 fi
 
 #  set -x
+
+
+if [[ -n "${solr_baseurl}" && -z "${svc_map[solr]}" ]]; then
+  echo "Warning: -solr or -extsolr supplied but no solr service definition"
+  exit 1
+fi
+
+if [ -n "${dispatching_index}" -a -z "${solr_baseurl}" ]; then
+  echo "Error: -dispatching requires -solr or -extsolr"
+  exit 1
+fi
 
 for name in ${svc_list[@]}; do
   case "$verb" in
