Run from copy of fat jar to protect from project builds while running

diff --git a/bin/runservice b/bin/runservice
--- a/bin/runservice
+++ b/bin/runservice
@@ -36,22 +36,38 @@ trim() {
   echo `echo $1 | sed -e 's/^ *//' -e 's/ *$//'`
 }
 
-offline=
-app_args=
-java_args="-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dorg.springframework.boot.logging.LoggingSystem=none"
-run_dir=
-runjar=
-props=
+# remove temp jar file when exit
+cleanup() {
+  /bin/rm -f $tmp_jar
+}
+
+fat_jar="current-with-deps.jar"
+tmp_jar="runlib/$fat_jar"
 
 # local files that should be served as part of the cluster config if running
 # as a cfgsvc
 cluster_files="config/common.xml"
-
+# local files not part of cluster config
 local_files="config/lockss.txt config/lockss.opt"
+
 tdb_dirs=tdbxml/prod
+
 upass="lockss-u:lockss-p@"
 
+
+java_args="-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dorg.springframework.boot.logging.LoggingSystem=none"
+
+offline=
+app_args=
+
+run_dir=
+runjar=
+props=
+
 cfg_svc=
+
+# Clean up if script is interrupted or terminated.
+trap "cleanup" SIGINT SIGTERM 1 0
 
 while [ -n "$1" ]; do
   case "$1" in
@@ -160,8 +176,10 @@ if [ -z $runjar ]; then
 else
   # Run the service from the fat jar
   # Ensure that the fat jar is up-to-date
-  if [ ! target/current-with-deps.jar -ot target/build-info ]; then
-    java $java_args -jar target/current-with-deps.jar $app_args || exit 1
+  if [ ! target/$fat_jar -ot target/build-info ]; then
+    mkdir -p runlib
+    cp target/$fat_jar runlib
+    java $java_args -jar runlib/$fat_jar $app_args || exit 1
     exit 0
   else
     echo "Not running service: Either packaged jar does not exist or is out of date."
